[2024-02-23T03:28:49.512+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:28:49.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:28:49.542+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:28:49.538+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:28:54.136+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:28:54.130+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    'user': Variable.get("pg-user"),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable pg-user does not exist'
[2024-02-23T03:28:54.137+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:28:54.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 4.720 seconds
[2024-02-23T03:29:25.115+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:29:25.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:29:25.153+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:29:25.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:29:27.469+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:29:27.440+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    'user': Variable.get("pg-user"),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable pg-user does not exist'
[2024-02-23T03:29:27.786+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:29:27.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 2.899 seconds
[2024-02-23T03:29:59.365+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:30:00.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:30:00.238+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:30:00.054+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:30:02.585+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:30:02.577+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    'user': Variable.get("pg-user"),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable pg-user does not exist'
[2024-02-23T03:30:02.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:30:02.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 3.359 seconds
[2024-02-23T03:30:32.908+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:30:32.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:30:32.915+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:30:32.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:30:33.538+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:30:33.535+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    'user': Variable.get("pg-user"),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable pg-user does not exist'
[2024-02-23T03:30:33.539+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:30:33.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.660 seconds
[2024-02-23T03:31:04.271+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:31:04.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:31:04.314+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:31:04.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:31:05.037+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:31:05.032+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    'user': Variable.get("pg-user"),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable pg-user does not exist'
[2024-02-23T03:31:05.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:31:05.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.811 seconds
[2024-02-23T03:31:35.492+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:31:35.503+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:31:35.509+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:31:35.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:31:36.421+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:31:36.413+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    'user': Variable.get("pg-user"),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable pg-user does not exist'
[2024-02-23T03:31:36.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:31:36.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.987 seconds
[2024-02-23T03:32:07.945+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:32:07.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:32:07.956+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:32:07.953+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:32:11.319+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:32:11.293+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 13, in <module>
    'user': Variable.get("pg-user"),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable pg-user does not exist'
[2024-02-23T03:32:11.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:32:11.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 3.509 seconds
[2024-02-23T03:32:41.984+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:32:41.989+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:32:41.993+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:32:41.991+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:32:43.166+0000] {processor.py:840} INFO - DAG(s) 'Data-pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:32:43.711+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:32:43.710+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:Data-pipeline
[2024-02-23T03:32:43.717+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:32:43.717+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:Data-pipeline
[2024-02-23T03:32:43.720+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:32:43.720+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:Data-pipeline
[2024-02-23T03:32:43.721+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:32:43.721+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-23T03:32:43.809+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:32:43.809+0000] {dag.py:3058} INFO - Creating ORM DAG for Data-pipeline
[2024-02-23T03:32:43.830+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:32:43.830+0000] {dag.py:3823} INFO - Setting next_dagrun for Data-pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2024-02-23T03:32:43.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 1.886 seconds
[2024-02-23T03:33:14.296+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:33:14.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:33:14.300+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:33:14.300+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:33:14.481+0000] {processor.py:840} INFO - DAG(s) 'Data-pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:33:14.491+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:33:14.491+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-23T03:33:14.502+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:33:14.502+0000] {dag.py:3823} INFO - Setting next_dagrun for Data-pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2024-02-23T03:33:14.517+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.227 seconds
[2024-02-23T03:33:44.861+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:33:44.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:33:44.866+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:33:44.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:33:45.056+0000] {processor.py:840} INFO - DAG(s) 'Data-pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:33:45.065+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:33:45.065+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-23T03:33:45.075+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:33:45.075+0000] {dag.py:3823} INFO - Setting next_dagrun for Data-pipeline to 2024-02-21 00:00:00+00:00, run_after=2024-02-22 00:00:00+00:00
[2024-02-23T03:33:45.083+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.227 seconds
[2024-02-23T03:34:15.428+0000] {processor.py:161} INFO - Started process (PID=337) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:34:15.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:34:15.433+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:34:15.433+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:34:15.629+0000] {processor.py:840} INFO - DAG(s) 'Data-pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:34:15.639+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:34:15.639+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-23T03:34:15.653+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:34:15.653+0000] {dag.py:3823} INFO - Setting next_dagrun for Data-pipeline to 2024-02-23 00:00:00+00:00, run_after=2024-02-24 00:00:00+00:00
[2024-02-23T03:34:15.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.249 seconds
[2024-02-23T03:34:45.852+0000] {processor.py:161} INFO - Started process (PID=349) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:34:45.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:34:45.856+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:34:45.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:34:46.098+0000] {processor.py:840} INFO - DAG(s) 'Data-pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:34:46.112+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:34:46.112+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-23T03:34:46.128+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:34:46.128+0000] {dag.py:3823} INFO - Setting next_dagrun for Data-pipeline to 2024-02-23 00:00:00+00:00, run_after=2024-02-24 00:00:00+00:00
[2024-02-23T03:34:46.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.299 seconds
[2024-02-23T03:35:16.438+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:35:16.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:35:16.441+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:35:16.440+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:35:16.627+0000] {processor.py:840} INFO - DAG(s) 'Data-pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:35:16.637+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:35:16.637+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-23T03:35:16.656+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:35:16.655+0000] {dag.py:3823} INFO - Setting next_dagrun for Data-pipeline to 2024-02-23 00:00:00+00:00, run_after=2024-02-24 00:00:00+00:00
[2024-02-23T03:35:16.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.234 seconds
[2024-02-23T03:35:46.871+0000] {processor.py:161} INFO - Started process (PID=372) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:35:46.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:35:46.874+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:35:46.873+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:35:47.156+0000] {processor.py:840} INFO - DAG(s) 'Data-pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:35:47.166+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:35:47.166+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-23T03:35:47.178+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:35:47.178+0000] {dag.py:3823} INFO - Setting next_dagrun for Data-pipeline to 2024-02-23 00:00:00+00:00, run_after=2024-02-24 00:00:00+00:00
[2024-02-23T03:35:47.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.320 seconds
[2024-02-23T03:36:17.328+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:36:17.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:36:17.331+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:36:17.331+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:36:17.589+0000] {processor.py:840} INFO - DAG(s) 'Data-pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:36:17.602+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:36:17.602+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-23T03:36:17.764+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:36:17.762+0000] {dag.py:3823} INFO - Setting next_dagrun for Data-pipeline to 2024-02-23 00:00:00+00:00, run_after=2024-02-24 00:00:00+00:00
[2024-02-23T03:36:17.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.505 seconds
[2024-02-23T03:36:48.032+0000] {processor.py:161} INFO - Started process (PID=397) to work on /opt/airflow/dags/dag.py
[2024-02-23T03:36:48.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-02-23T03:36:48.035+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:36:48.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-02-23T03:36:48.335+0000] {processor.py:840} INFO - DAG(s) 'Data-pipeline' retrieved from /opt/airflow/dags/dag.py
[2024-02-23T03:36:48.356+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:36:48.356+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-23T03:36:48.369+0000] {logging_mixin.py:188} INFO - [2024-02-23T03:36:48.369+0000] {dag.py:3823} INFO - Setting next_dagrun for Data-pipeline to 2024-02-23 00:00:00+00:00, run_after=2024-02-24 00:00:00+00:00
[2024-02-23T03:36:48.378+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag.py took 0.352 seconds
